import { useEffect, useState } from 'react'
import { useAuth } from '../../context/AuthContext'
import { supabase, ExamSession, Exam, QuestionGrade } from '../../lib/supabase'
import { isLemmaConfigured, runAiGrading } from '../../lib/lemma'
import { useParams } from 'react-router-dom'
import { Download, User, Clock, CheckCircle, ChevronDown, ChevronUp, Save, Sparkles } from 'lucide-react'
import Layout from '../../components/layout/Layout'
import jsPDF from 'jspdf'
import toast from 'react-hot-toast'

export default function Submissions() {
  const { profile } = useAuth()
  const { examId } = useParams()
  const [sessions, setSessions] = useState<ExamSession[]>([])
  const [exam, setExam] = useState<Exam | null>(null)
  const [exams, setExams] = useState<Exam[]>([])
  const [selectedExam, setSelectedExam] = useState<string>(examId || '')
  const [loading, setLoading] = useState(true)
  const [expandedId, setExpandedId] = useState<string | null>(null)
  const [savingGrade, setSavingGrade] = useState<string | null>(null)
  const [aiGrading, setAiGrading] = useState<string | null>(null)

  useEffect(() => { if (profile?.id) fetchExams() }, [profile])
  useEffect(() => { if (selectedExam) fetchSessions(selectedExam) }, [selectedExam])

  const fetchExams = async () => {
    const { data } = await supabase.from('exams').select('*').eq('teacher_id', profile!.id).order('created_at', { ascending: false })
    setExams(data || [])
    if (!selectedExam && data && data.length > 0) setSelectedExam(data[0].id)
    setLoading(false)
  }

  const fetchSessions = async (eid: string) => {
    const { data: examData } = await supabase.from('exams').select('*').eq('id', eid).single()
    setExam(examData)
    const { data } = await supabase.from('exam_sessions').select('*, student:profiles(*)').eq('exam_id', eid).eq('status', 'submitted').order('submitted_at', { ascending: false })
    setSessions(data || [])
  }

  const downloadPDF = (session: ExamSession) => {
    if (!exam) return
    const doc = new jsPDF()
    doc.setFontSize(20)
    doc.setFont('helvetica', 'bold')
    doc.text('SwarLekh — Exam Submission', 20, 20)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'normal')
    doc.text(`Exam: ${exam.title}`, 20, 35)
    doc.text(`Subject: ${exam.subject}`, 20, 43)
    doc.text(`Student: ${(session.student as any)?.name || 'Student'}`, 20, 51)
    doc.text(`Submitted: ${session.submitted_at ? new Date(session.submitted_at).toLocaleString() : 'N/A'}`, 20, 59)
    doc.line(20, 65, 190, 65)
    let y = 75
    const questions = exam.questions || []
    questions.forEach((q, i) => {
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(12)
      const qLines = doc.splitTextToSize(`Q${i+1} (${q.marks} marks): ${q.question}`, 165)
      doc.text(qLines, 20, y)
      y += qLines.length * 7 + 4
      doc.setFont('helvetica', 'normal')
      const ans = session.answers?.[q.id] || 'No answer provided'
      const aLines = doc.splitTextToSize(`Answer: ${ans}`, 165)
      doc.text(aLines, 20, y)
      y += aLines.length * 7 + 10
      if (y > 260) { doc.addPage(); y = 20 }
    })
    doc.setFontSize(9)
    doc.setTextColor(150)
    doc.text('Generated by SwarLekh — Accessible Exam Platform', 20, 285)
    doc.save(`SwarLekh-${(session.student as any)?.name || 'student'}-${exam.title}.pdf`)
    toast.success('PDF downloaded!')
  }

  const updateGradeField = (sessionId: string, questionId: string, field: keyof QuestionGrade, value: any) => {
    setSessions(prev => prev.map(s => {
      if (s.id !== sessionId) return s
      const grading = { ...(s.grading || {}) }
      grading[questionId] = { ...(grading[questionId] || {}), [field]: value }
      return { ...s, grading }
    }))
  }

  const runGrading = async (session: ExamSession) => {
    if (!exam || !profile) return
    setAiGrading(session.id)
    try {
      const { results, skipped } = await runAiGrading(
        exam,
        session,
        { name: profile.name, email: profile.email, institution: profile.institution },
        { name: session.student?.name || 'Student', email: session.student?.email || '', institution: session.student?.institution }
      )
      const grading = { ...(session.grading || {}) }
      Object.entries(results).forEach(([qId, r]) => {
        grading[qId] = { ...(grading[qId] || {}), ai_score: r.ai_score, ai_feedback: r.ai_feedback }
        if (exam.grading_mode === 'ai') grading[qId].final_score = r.ai_score
      })
      const { error } = await supabase.from('exam_sessions').update({ grading }).eq('id', session.id)
      if (error) throw error
      setSessions(prev => prev.map(s => s.id === session.id ? { ...s, grading } : s))
      const gradedCount = Object.keys(results).length
      const skippedCount = Object.keys(skipped).length
      toast.success(`AI graded ${gradedCount} question${gradedCount === 1 ? '' : 's'}${skippedCount ? `, skipped ${skippedCount}` : ''}`)
    } catch (err: any) {
      toast.error(err?.message || 'AI grading failed. Check that the Lemma pod is running and reachable.')
    } finally {
      setAiGrading(null)
    }
  }

  const saveGrading = async (session: ExamSession) => {
    setSavingGrade(session.id)
    // final_score for manual mode = whatever the teacher entered per question.
    const grading = { ...(session.grading || {}) }
    Object.keys(grading).forEach(qId => {
      const g = grading[qId]
      if (g.manual_score !== undefined && g.manual_score !== null) {
        grading[qId] = { ...g, final_score: g.manual_score }
      }
    })
    const { error } = await supabase.from('exam_sessions').update({ grading }).eq('id', session.id)
    setSavingGrade(null)
    if (error) {
      toast.error('Could not save grading. Make sure ADD_FEATURES.sql has been run in Supabase.')
      return
    }
    toast.success('Grading saved')
  }

  const totalMarks = (exam: Exam | null) => (exam?.questions || []).reduce((sum, q) => sum + (q.marks || 0), 0)
  const scoredMarks = (session: ExamSession) => Object.values(session.grading || {}).reduce((sum, g) => sum + (g.final_score ?? g.manual_score ?? 0), 0)

  return (
    <Layout>
      <div className="p-8">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Submissions</h1>
        <p className="text-gray-500 mb-6">Review and download student exam submissions</p>

        {/* Exam Selector */}
        <div className="card-p mb-6">
          <label className="block text-sm font-medium text-gray-700 mb-2">Select Exam</label>
          <select className="input-field max-w-md" value={selectedExam} onChange={e => setSelectedExam(e.target.value)}>
            {exams.map(e => <option key={e.id} value={e.id}>{e.title} — {e.subject}</option>)}
          </select>
        </div>

        {/* Submissions List */}
        <div className="card-p">
          <div className="flex items-center justify-between mb-5">
            <h2 className="text-lg font-semibold text-gray-900">
              {exam?.title || 'Select an exam'} — {sessions.length} submission{sessions.length !== 1 ? 's' : ''}
            </h2>
          </div>
          {loading ? (
            <div className="text-center py-12 text-gray-400">Loading...</div>
          ) : sessions.length === 0 ? (
            <div className="text-center py-16 text-gray-400">
              <CheckCircle size={48} className="mx-auto mb-4 text-gray-300" />
              <p className="text-lg">No submissions yet for this exam</p>
            </div>
          ) : (
            <div className="space-y-4">
              {sessions.map(session => (
                <div key={session.id} className="p-5 rounded-xl border border-gray-200 hover:border-green-200 transition-all">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 bg-green-100 rounded-full flex items-center justify-center">
                        <User size={18} className="text-green-600" />
                      </div>
                      <div>
                        <div className="font-semibold text-gray-900">{(session.student as any)?.name || 'Student'}</div>
                        <div className="flex items-center gap-3 text-sm text-gray-500 mt-0.5">
                          <span className="flex items-center gap-1"><Clock size={14} />
                            {session.submitted_at ? new Date(session.submitted_at).toLocaleString() : 'N/A'}
                          </span>
                          <span className="badge-green">Submitted</span>
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      {exam && (
                        <span className="text-sm font-medium text-gray-500">
                          {scoredMarks(session)} / {totalMarks(exam)} marks
                        </span>
                      )}
                      <button onClick={() => downloadPDF(session)} className="btn-primary flex items-center gap-2">
                        <Download size={18} />PDF
                      </button>
                      <button onClick={() => setExpandedId(id => id === session.id ? null : session.id)}
                        className="btn-secondary flex items-center gap-2 min-h-0 py-2.5 px-4">
                        {expandedId === session.id ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                        Grade
                      </button>
                    </div>
                  </div>

                  {expandedId !== session.id && (
                    <div className="mt-4 pt-4 border-t border-gray-100 space-y-3">
                      {(exam?.questions || []).slice(0,2).map((q, i) => (
                        <div key={i} className="bg-gray-50 rounded-lg p-3">
                          <div className="text-sm font-medium text-gray-700 mb-1">Q{i+1}: {q.question}</div>
                          <div className="text-sm text-gray-600">{session.answers?.[q.id] || 'No answer'}</div>
                        </div>
                      ))}
                      {(exam?.questions || []).length > 2 && (
                        <p className="text-sm text-gray-400">+{(exam?.questions || []).length - 2} more answers in PDF</p>
                      )}
                    </div>
                  )}

                  {expandedId === session.id && (
                    <div className="mt-4 pt-4 border-t border-gray-100 space-y-4">
                      {exam?.grading_mode !== 'manual' && (
                        isLemmaConfigured() ? (
                          <button onClick={() => runGrading(session)} disabled={aiGrading === session.id}
                            className="btn-secondary flex items-center gap-2 min-h-0 py-2.5 px-4 mb-2">
                            <Sparkles size={16} />{aiGrading === session.id ? 'AI grading...' : 'Run AI Grading'}
                          </button>
                        ) : (
                          <div className="text-xs text-gray-400 italic mb-2">
                            AI grading needs the Lemma pod connected (VITE_LEMMA_* env vars not set) — grade manually below in the meantime.
                          </div>
                        )
                      )}
                      {(exam?.questions || []).map((q, i) => {
                        const g: QuestionGrade = session.grading?.[q.id] || {}
                        return (
                          <div key={i} className="bg-gray-50 rounded-lg p-4">
                            <div className="text-sm font-medium text-gray-700 mb-1">Q{i+1} ({q.marks} marks): {q.question}</div>
                            <div className="text-sm text-gray-600 mb-3">{session.answers?.[q.id] || 'No answer'}</div>

                            {(g.ai_score !== undefined || g.ai_feedback) ? (
                              <div className="text-xs bg-purple-50 border border-purple-200 rounded-lg p-2 mb-3">
                                <span className="font-semibold text-purple-700">AI suggested: {g.ai_score ?? '—'}/{q.marks}</span>
                                {g.ai_feedback && <p className="text-purple-600 mt-1">{g.ai_feedback}</p>}
                              </div>
                            ) : exam?.grading_mode !== 'manual' && (
                              <div className="text-xs text-gray-400 italic mb-3">Not graded by AI yet — requires the Lemma grading agent to be wired in.</div>
                            )}

                            <div className="grid grid-cols-3 gap-3 items-end">
                              <div>
                                <label className="text-xs font-medium text-gray-600">Score (out of {q.marks})</label>
                                <input type="number" min={0} max={q.marks} className="input-field text-sm py-2 min-h-0 mt-1"
                                  value={g.manual_score ?? ''}
                                  onChange={e => updateGradeField(session.id, q.id, 'manual_score', e.target.value === '' ? undefined : Math.max(0, Math.min(q.marks, +e.target.value)))} />
                              </div>
                              <div className="col-span-2">
                                <label className="text-xs font-medium text-gray-600">Remarks (shown to student)</label>
                                <input className="input-field text-sm py-2 min-h-0 mt-1" placeholder="Optional feedback for the student"
                                  value={g.teacher_remarks ?? ''}
                                  onChange={e => updateGradeField(session.id, q.id, 'teacher_remarks', e.target.value)} />
                              </div>
                            </div>
                          </div>
                        )
                      })}
                      <button onClick={() => saveGrading(session)} disabled={savingGrade === session.id}
                        className="btn-success flex items-center gap-2">
                        <Save size={16} />{savingGrade === session.id ? 'Saving...' : 'Save Grading'}
                      </button>
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </Layout>
  )
}
